// 自动生成的演示钓点种子数据（常熟地区 8 个 published 钓点）
// 由 gen-seed.js 从 fishing.db 导出。initDatabase 在库为空时自动灌入。
// 请勿手改；如需更新演示数据，请修改本地库后重新生成。

const DEMO_SPOTS = [
  {
    id: "329482b3-35b4-4be2-9616-71e4bcf1bc8e",
    name: "尚湖水库",
    province_id: null,
    city_id: null,
    district_id: null,
    province: null,
    city: "常熟市",
    district: "尚湖镇",
    address: "尚湖风景区北门钓区",
    latitude: 31.6612,
    longitude: 120.6815,
    water_type: "reservoir",
    target_fish: "鲫鱼 / 鲤鱼 / 草鱼",
    avg_depth: 3.5,
    best_time: "清晨 5-8 点 / 傍晚 17-20 点",
    best_season: "春秋",
    fee_type: "daily",
    fee_price: "50 元/天",
    parking: 1,
    restroom: 1,
    shade: 1,
    rod_limit: "限 5.4 米以内",
    flood_warning: null,
    description: "常熟最大的水库型钓场，水面开阔、鱼种丰富，适合台钓与抛竿。湖边有步道与停车场，新手友好。",
    images: "[]",
    status: "published",
    fishing_index: 80,
    weather_data: "{\"temperature\":27,\"humidity\":90,\"pressure\":1002,\"wind_direction\":\"东风\",\"wind_power\":\"2级\",\"precipitation\":0,\"fishing_index\":80,\"fishing_level\":\"优\",\"weather\":\"雾\",\"obs_time\":\"2026-07-19T01:00+08:00\"}",
    favorites_count: 1,
    catches_count: 1,
    comments_count: 1,
    submitter_id: null
  },
  {
    id: "6f57c5f4-5cca-4540-a86e-1538d8f7278c",
    name: "昆承湖",
    province_id: null,
    city_id: null,
    district_id: null,
    province: null,
    city: "常熟市",
    district: "琴川街道",
    address: "昆承湖西岸亲水栈道",
    latitude: 31.6218,
    longitude: 120.8035,
    water_type: "lake",
    target_fish: "草鱼 / 青鱼 / 翘嘴",
    avg_depth: 4.2,
    best_time: "清晨 / 夜间",
    best_season: "夏秋",
    fee_type: "free",
    fee_price: "免费（需登记）",
    parking: 1,
    restroom: 0,
    shade: 0,
    rod_limit: "不限",
    flood_warning: null,
    description: "城市内湖，免费开放，夜钓人气旺。大青大草偶尔爆护，注意防蚊虫。",
    images: "[]",
    status: "published",
    fishing_index: 80,
    weather_data: "{\"temperature\":27,\"humidity\":90,\"pressure\":1002,\"wind_direction\":\"东风\",\"wind_power\":\"2级\",\"precipitation\":0,\"fishing_index\":80,\"fishing_level\":\"优\",\"weather\":\"雾\",\"obs_time\":\"2026-07-19T01:00+08:00\"}",
    favorites_count: 0,
    catches_count: 0,
    comments_count: 0,
    submitter_id: null
  },
  {
    id: "042d31fa-37bc-4ee5-b783-09efc42eeaf2",
    name: "长江常熟段",
    province_id: null,
    city_id: null,
    district_id: null,
    province: null,
    city: "常熟市",
    district: "碧溪新区",
    address: "浒浦渔港上游江堤",
    latitude: 31.7125,
    longitude: 120.9235,
    water_type: "river",
    target_fish: "鲻鱼 / 鳜鱼 / 江鲢",
    avg_depth: 8,
    best_time: "涨潮前后 2 小时",
    best_season: "春夏",
    fee_type: "other",
    fee_price: "江边野钓免费",
    parking: 1,
    restroom: 1,
    shade: 0,
    rod_limit: "海竿为宜",
    flood_warning: null,
    description: "长江下游野钓点，水流急、鱼力道足。涨落潮时段鱼口最好，注意安全与潮汐。",
    images: "[]",
    status: "published",
    fishing_index: 80,
    weather_data: "{\"temperature\":27,\"humidity\":90,\"pressure\":1002,\"wind_direction\":\"东风\",\"wind_power\":\"2级\",\"precipitation\":0,\"fishing_index\":80,\"fishing_level\":\"优\",\"weather\":\"雾\",\"obs_time\":\"2026-07-19T01:00+08:00\"}",
    favorites_count: 0,
    catches_count: 0,
    comments_count: 0,
    submitter_id: null
  },
  {
    id: "02d259dd-d0f5-4f0e-9f80-3d7a6e2887bc",
    name: "沙家浜芦苇荡",
    province_id: null,
    city_id: null,
    district_id: null,
    province: null,
    city: "常熟市",
    district: "沙家浜镇",
    address: "沙家浜景区内芦苇水道",
    latitude: 31.5328,
    longitude: 120.7125,
    water_type: "pond",
    target_fish: "鲫鱼 / 黑鱼 / 黄颡",
    avg_depth: 2,
    best_time: "清晨 / 阴天",
    best_season: "春秋",
    fee_type: "daily",
    fee_price: "40 元/天",
    parking: 1,
    restroom: 1,
    shade: 1,
    rod_limit: "限 4.5 米",
    flood_warning: null,
    description: "芦苇荡密布的小型塘口，黑鱼藏身水草边。环境清幽，适合休闲野钓。",
    images: "[]",
    status: "published",
    fishing_index: 80,
    weather_data: "{\"temperature\":27,\"humidity\":90,\"pressure\":1002,\"wind_direction\":\"东风\",\"wind_power\":\"2级\",\"precipitation\":0,\"fishing_index\":80,\"fishing_level\":\"优\",\"weather\":\"雾\",\"obs_time\":\"2026-07-19T01:00+08:00\"}",
    favorites_count: 0,
    catches_count: 0,
    comments_count: 0,
    submitter_id: null
  },
  {
    id: "39311bbe-9009-4edd-a8e5-ab0eb9befb4c",
    name: "白茆塘",
    province_id: null,
    city_id: null,
    district_id: null,
    province: null,
    city: "常熟市",
    district: "古里镇",
    address: "白茆塘支流水闸边",
    latitude: 31.6018,
    longitude: 120.7845,
    water_type: "stream",
    target_fish: "翘嘴 / 白条 / 马口",
    avg_depth: 1.5,
    best_time: "清晨 / 傍晚",
    best_season: "夏",
    fee_type: "free",
    fee_price: "免费",
    parking: 0,
    restroom: 0,
    shade: 0,
    rod_limit: "路亚竿",
    flood_warning: null,
    description: "缓流水道，路亚翘嘴和白条的好地方。水浅鱼小，讲究手感与操作。",
    images: "[]",
    status: "published",
    fishing_index: 80,
    weather_data: "{\"temperature\":27,\"humidity\":90,\"pressure\":1002,\"wind_direction\":\"东风\",\"wind_power\":\"2级\",\"precipitation\":0,\"fishing_index\":80,\"fishing_level\":\"优\",\"weather\":\"雾\",\"obs_time\":\"2026-07-19T01:00+08:00\"}",
    favorites_count: 0,
    catches_count: 0,
    comments_count: 0,
    submitter_id: null
  },
  {
    id: "b92c0963-cda3-465b-91df-aa28c4c9a0bf",
    name: "望虞河",
    province_id: null,
    city_id: null,
    district_id: null,
    province: null,
    city: "常熟市",
    district: "辛庄镇",
    address: "望虞河节制闸下游",
    latitude: 31.6805,
    longitude: 120.6025,
    water_type: "river",
    target_fish: "鲈鱼 / 鳜鱼 / 鲤鱼",
    avg_depth: 5,
    best_time: "清晨 / 雨后",
    best_season: "春秋",
    fee_type: "free",
    fee_price: "免费",
    parking: 1,
    restroom: 0,
    shade: 1,
    rod_limit: "不限",
    flood_warning: null,
    description: "连通长江与太湖的干线河道，鲈鳜资源丰富。雨后水流增氧时鱼口最活跃。",
    images: "[]",
    status: "published",
    fishing_index: 80,
    weather_data: "{\"temperature\":27,\"humidity\":90,\"pressure\":1002,\"wind_direction\":\"东风\",\"wind_power\":\"2级\",\"precipitation\":0,\"fishing_index\":80,\"fishing_level\":\"优\",\"weather\":\"雾\",\"obs_time\":\"2026-07-19T01:00+08:00\"}",
    favorites_count: 0,
    catches_count: 0,
    comments_count: 0,
    submitter_id: null
  },
  {
    id: "3f5d93dd-68bf-4ffc-a9d8-a5a6668191cd",
    name: "琴湖",
    province_id: null,
    city_id: null,
    district_id: null,
    province: null,
    city: "常熟市",
    district: "琴川街道",
    address: "琴湖湿地木栈道",
    latitude: 31.6505,
    longitude: 120.7525,
    water_type: "pond",
    target_fish: "鲤鱼 / 鲫鱼 / 鲢鱼",
    avg_depth: 2.5,
    best_time: "清晨 / 傍晚",
    best_season: "春秋",
    fee_type: "daily",
    fee_price: "30 元/天",
    parking: 1,
    restroom: 1,
    shade: 1,
    rod_limit: "限 3.6-4.5 米",
    flood_warning: null,
    description: "市中心的景观湖，交通方便、设施齐全。周末家庭休闲钓首选。",
    images: "[]",
    status: "published",
    fishing_index: 80,
    weather_data: "{\"temperature\":27,\"humidity\":90,\"pressure\":1002,\"wind_direction\":\"东风\",\"wind_power\":\"2级\",\"precipitation\":0,\"fishing_index\":80,\"fishing_level\":\"优\",\"weather\":\"雾\",\"obs_time\":\"2026-07-19T01:00+08:00\"}",
    favorites_count: 0,
    catches_count: 0,
    comments_count: 0,
    submitter_id: null
  },
  {
    id: "babbfc16-c5e1-4357-96d1-58c511546bea",
    name: "浒浦闸口",
    province_id: null,
    city_id: null,
    district_id: null,
    province: null,
    city: "常熟市",
    district: "海虞镇",
    address: "浒浦船闸外侧引水渠",
    latitude: 31.7305,
    longitude: 120.8525,
    water_type: "river",
    target_fish: "鲻鱼 / 鲈鱼",
    avg_depth: 6,
    best_time: "潮水活跃时",
    best_season: "夏",
    fee_type: "other",
    fee_price: "野钓免费",
    parking: 0,
    restroom: 0,
    shade: 0,
    rod_limit: "海竿",
    flood_warning: null,
    description: "闸口引水渠，水流带氧、聚鱼明显。地势湿滑，务必注意脚下安全。",
    images: "[]",
    status: "published",
    fishing_index: 80,
    weather_data: "{\"temperature\":27,\"humidity\":90,\"pressure\":1002,\"wind_direction\":\"东风\",\"wind_power\":\"2级\",\"precipitation\":0,\"fishing_index\":80,\"fishing_level\":\"优\",\"weather\":\"雾\",\"obs_time\":\"2026-07-19T01:00+08:00\"}",
    favorites_count: 0,
    catches_count: 0,
    comments_count: 0,
    submitter_id: null
  }
];

function seedDemoSpots(dbWrap) {
  const row = dbWrap.prepare('SELECT COUNT(*) AS c FROM fishing_spots').get();
  if (row && row.c > 0) return false; // 已有数据则跳过
  const cols = ["id","name","province_id","city_id","district_id","province","city","district","address","latitude","longitude","water_type","target_fish","avg_depth","best_time","best_season","fee_type","fee_price","parking","restroom","shade","rod_limit","flood_warning","description","images","status","fishing_index","weather_data","favorites_count","catches_count","comments_count","submitter_id"];
  const placeholders = cols.map(() => '?').join(',');
  const stmt = dbWrap.prepare(
    `INSERT INTO fishing_spots (${cols.join(',')}) VALUES (${placeholders})`
  );
  for (const s of DEMO_SPOTS) {
    stmt.run(...cols.map(c => (s[c] === undefined ? null : s[c])));
  }
  console.log('[DB] 已 seed 演示钓点:', DEMO_SPOTS.length);
  return true;
}

module.exports = { DEMO_SPOTS, seedDemoSpots };
